# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ea17d74a35e97722560c23e100c76798b107e8defb35818ce7cd45c7a556c40451f96cc86201f940df68698a2173c28df59286235dbbf4a279692e9f0b94b32

test:
  secret_key_base: b539e5fcef6cd2c05dd716d2d45a3cafebc620884b162bc83326c59e2a11660cd847fe5a77a63a713b5cd53c33e81994f0de0d72a9bc8bed05a59e4810607556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
